[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=68", "wheel", "setuptools_scm[toml]>=7.0,<9", "versionista>=1.1.0"]

[project]
authors = [{name = "NCI GDC", email = "support@nci-gdc.datacommons.io"}]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python"
]
dependencies = [
  "boto3",
  "boto3-stubs[s3]",
  "deepmerge",
  "elasticsearch[async]",
  "importlib-resources",
  "marshmallow~=3.0",
  "marshmallow-dataclass",
  "more-itertools",
  "numpy",
  "pyspark~=3.5.0",
  "python-json-logger",
  "tomli",
  "tomli-w",
  "typed-argument-parser",
  "typing-extensions",
  "indexclient @ git+https://github.com/NCI-GDC/indexclient.git@develop",
  "gdcmodels @ git+https://github.com/uc-cdis/mmrf-models.git#mmrf",
  "mutation-indexer-resource @ git+https://github.com/NCI-GDC/mutation-indexer-resource.git@1.0.0"
]
description = "ETL for mutation elasticsearch indices"
dynamic = ["version"]
license = {file = "LICENSE"}
name = "gdc-mutation-indexer"
requires-python = "~=3.13.0"

[project.optional-dependencies]
client = ["halo", "pex", "wheel"]
dev = ["click", "coverage[toml]", "deepdiff", "inflect", "pytest"]

[project.scripts]
mutation-indexer = "mutation_indexer.client:main [client]"

[project.urls]
repository = "https://github.com/NCI-GDC/gdc-mutation-indexer"

[tool.coverage.html]
directory = "docs/htmlcov"
title = "mutation-indexer coverage report"

[tool.coverage.run]
branch = true
source = ["mutation_indexer"]

[tool.mypy]
plugins = ["marshmallow_dataclass.mypy"]

[tool.pytest.ini_options]
addopts = "-rflv"
markers = [
  "ssm_occurrence_centric_ssm_subtree",
  "gene_centric_ssm_subtree",
  "cnv_occurrence_centric_cnv_subtree",
  "case_centric_ssm_subtree",
  "case_schema_dependent: Marks a test which is dependent on an input case schema."
]
minversion = "6.0"
testpaths = ["tests/unit", "tests/integration"]

[tool.ruff]
line-length = 95
src = ["src", "tests"]
target-version = "py313"

[tool.ruff.lint]
# see https://docs.astral.sh/ruff/rules/
select = [
  "E", # pydocstyle errors
  "F", # pyflakes
  "I", # isort
  "N", # pep8 naming
  "RUF", # ruff specific rules
  "UP", # pyupgrade
  "W" # pydocstyle warnings
]
ignore = [
  "E501",
  "N815"
]

[tool.ruff.lint.flake8-import-conventions.aliases]
"pyspark.sql.functions" = "F"

[tool.ruff.lint.isort]
known-first-party = ["mutation_indexer", "tests"]

[tool.ruff.lint.pep8-naming]
extend-ignore-names = ["F"]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.setuptools_scm]
local_scheme = "versionista-local-format"
version_scheme = "versionista-format"

[tool.tox]
requires = ["tox>=4.21"]

[tool.tox.env.coverage]
commands = [["coverage", "html"], ["coverage", "xml"]]
deps = ["-crequirements.txt", "coverage[toml]"]
skip_install = true

[tool.tox.env.pex]
commands = [
  [
    "pex",
    ".[client]",
    "--no-strip-pex-env",
    "--python=python{env:SCIE_PYTHON_VERSION}",
    "--entry-point=mutation_indexer.client",
    "--constraints=requirements.txt",
    "--output-file=mutation-indexer",
    "--scie=eager",
    "--scie-platform={env:SCIE_PLATFORM}",
    "--scie-python-version={env:SCIE_PYTHON_VERSION}",
    "--find-links=wheels/",
    "--pre",
    "--runtime-pex-root=/tmp/pex"
  ],
  [
    "pex",
    ".",
    "--no-strip-pex-env",
    "--python=python{env:SCIE_PYTHON_VERSION}",
    "--constraints=requirements.txt",
    "--output-file=driver-all",
    "--scie=eager",
    "--scie-platform={env:SCIE_PLATFORM}",
    "--scie-python-version={env:SCIE_PYTHON_VERSION}",
    "--find-links=wheels/",
    "--pre",
    "--runtime-pex-root=/tmp/pex"
  ]
]
deps = ["-crequirements.txt", "pex"]
pass_env = ["PEX_ROOT", "SCIE_BASE", "SSH_AUTH_SOCK"]
skip_install = true

[tool.tox.env.pex.set_env]
SCIE_PLATFORM = {replace = "env", name = "SCIE_PLATFORM", default = "linux-x86_64"}
SCIE_PYTHON_VERSION = {replace = "env", name = "SCIE_PYTHON_VERSION", default = "3.13"}

[tool.tox.env.publish]
commands = [
  [
    "python",
    "-m",
    "setuptools_scm"
  ],
  [
    "python",
    "-m",
    "build"
  ],
  [
    "python",
    "-m",
    "twine",
    "check",
    "dist/*"
  ],
  [
    "python",
    "-m",
    "twine",
    "upload",
    "dist/*"
  ]
]
deps = ["setuptools_scm", "build", "twine"]
pass_env = ["TWINE_*"]
skip_install = true

[tool.tox.env.test]
allowlist_externals = ["bin/spark-install.sh"]
commands = [
  [
    "coverage",
    "run",
    "-m",
    "pytest",
    "-vv",
    {replace = "posargs", default = [
      "--junitxml=report.xml"
    ], extend = true}
  ],
  [
    "coverage",
    "report"
  ]
]
commands_pre = [["bin/spark-install.sh"]]
deps = ["-crequirements.txt", ".[dev,client]"]
pass_env = ["BOTO_CONFIG", "ES_*", "JAVA_HOME", "SPARK_HOME", "SSH_AUTH_SOCK"]

[tool.tox.env.test.set_env]
NO_PROXY = "localhost,postgres,127.0.0.1,::1,elasticsearch"
PIP_INDEX_URL = "https://nexus.osdc.io/repository/pypi-gdc-releases/simple"
no_proxy = "localhost,postgres,127.0.0.1,::1,elasticsearch"

[tool.tox.env_run_base]
base_python = ["py313"]
